### ISSUE TITLE
ValueError: Model file Kim_Vocal_2 not found in supported model files

### ISSUE THREAD

**Issue by tayyebhadi** [gaspardpetit/verbatim#39]
I get the following error when trying to run: **verbatim test.wav**   
 
(verbatim) PS C:\Users\thadi\Documents\Transcription\verbatim> verbatim test.wav      
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
Using CPU
INFO:verbatim.wav_conversion.convert_to_wav_ffmpeg:Converting C:\Users\thadi\Documents\Transcription\verbatim\test.wav to C:\Users\thadi\Documents\Transcription\verbatim\test.audio.wav
INFO:verbatim.wav_conversion.convert_to_wav_ffmpeg:ffmpeg started: ffmpeg -y -i C:\Users\thadi\Documents\Transcription\verbatim\test.wav -ac 1 -acodec pcm_s32le C:\Users\thadi\Documents\Transcription\verbatim\test.audio.wav
INFO:verbatim.wav_conversion.convert_to_wav_ffmpeg:Progress(frame=0, fps=0.0, size=287522816, time=datetime.timedelta(seconds=4492, microseconds=540000), bitrate=512.0, speed=10600.0)
INFO:verbatim.wav_conversion.convert_to_wav_ffmpeg:ffmpeg completed
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\verbatim\Scripts\verbatim.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\verbatim\__main__.py", line 123, in main
    pipeline.execute()
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\verbatim\pipeline.py", line 84, in execute
    f.execute(**self.context.to_dict())
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\verbatim\voice_isolation\isolate_voices_mdx.py", line 34, in execute
    separator.load_model(model_mdx)
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\audio_separator\separator\separator.py", line 686, in load_model
    model_filename, model_type, model_friendly_name, model_path, yaml_config_filename = self.download_model_files(model_filename)
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\audio_separator\separator\separator.py", line 536, in download_model_files
    raise ValueError(f"Model file {model_filename} not found in supported model files")
ValueError: Model file Kim_Vocal_2 not found in supported model files
(verbatim) PS C:\Users\thadi\Documents\Transcription\verbatim>

**Comment by gaspardpetit** [comment]
Thank you for reporting the issue - I have updated the dependencies and changed quite a few things. Please try the newer version and feel free to reopen this if it still does not work.

**Comment by tayyebhadi** [comment]
I keep getting the same error:
(verbatim) PS C:\Users\thadi\Documents\Transcription\verbatim> verbatim test.wav
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
Using CPU
INFO:verbatim.wav_conversion.convert_to_wav_ffmpeg:Converting C:\Users\thadi\Documents\Transcription\verbatim\test.wav to C:\Users\thadi\Documents\Transcription\verbatim\test.audio.wav
INFO:verbatim.wav_conversion.convert_to_wav_ffmpeg:ffmpeg started: ffmpeg -y -i C:\Users\thadi\Documents\Transcription\verbatim\test.wav -ac 1 -acodec pcm_s32le C:\Users\thadi\Documents\Transcription\verbatim\test.audio.wav
INFO:verbatim.wav_conversion.convert_to_wav_ffmpeg:Progress(frame=0, fps=0.0, size=287522816, time=datetime.timedelta(seconds=4492, microseconds=540000), bitrate=512.0, speed=11600.0)
INFO:verbatim.wav_conversion.convert_to_wav_ffmpeg:ffmpeg completed
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\verbatim\Scripts\verbatim.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\verbatim\__main__.py", line 117, in main
    pipeline.execute()
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\verbatim\pipeline.py", line 80, in execute
    f.execute(**self.context.to_dict())
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\verbatim\voice_isolation\isolate_voices_mdx.py", line 34, in execute
    separator.load_model(model_mdx)
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\audio_separator\separator\separator.py", line 672, in load_model
    model_filename, model_type, model_friendly_name, model_path, yaml_config_filename = self.download_model_files(model_filename)
  File "C:\ProgramData\anaconda3\envs\verbatim\lib\site-packages\audio_separator\separator\separator.py", line 588, in download_model_files
    raise ValueError(f"Model file {model_filename} not found in supported model files")
ValueError: Model file Kim_Vocal_2 not found in supported model files
